name: olie_skew-t_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - aom=3.9.1=he0c23c2_0
  - backports.zstd=1.2.0=py313h2a31948_0
  - blosc=1.21.6=hfd34d9b_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py313h3ebfc14_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.0=h91e5215_2
  - cartopy=0.25.0=py313hc90dcd4_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cycler=0.12.1=pyhcf101f3_2
  - dav1d=1.2.1=hcfcfb64_0
  - eccodes=2.44.0=h2bffdaa_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py313hd650c13_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - geos=3.14.1=hdade9fe_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf4=4.2.15=h1b1b6ef_5
  - hdf5=1.14.6=nompi_h89f0904_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h63175ca_0
  - idna=3.11=pyhd8ed1ab_0
  - jasper=4.2.8=hdd02f31_0
  - jpeg=9e=hcfcfb64_3
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libavif=1.3.0=he916da2_2
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_2
  - libcurl=8.17.0=h43ecb02_1
  - libdeflate=1.22=h2466b09_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libmpdec=4.0.0=h827c3e9_0
  - libnetcdf=4.9.3=nompi_ha45073a_102
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.53=h7351971_0
  - libpq=17.6=h652a1e2_0
  - libre2-11=2024.07.02=h0465865_4
  - libsqlite=3.51.1=hf5d6505_1
  - libssh2=1.11.1=h9aa295b_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - matplotlib=3.10.8=py313hfa70ccb_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - metpy=1.7.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=h2224204_0
  - mysql-libs=9.3.0=h809f9c2_0
  - numpy=2.4.0=py313hce7ae62_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313hc90dcd4_2
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py313h4212202_1
  - pint=0.25.2=pyhcf101f3_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - proj=9.7.1=h7b1ce8f_0
  - pygrib=2.1.8=py313h5a0afc0_0
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyproj=3.7.2=py313h24787ba_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pyside6=6.9.2=py313h151a370_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.13.11=h260b955_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.9.2=hd965823_2
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtshadertools=6.9.2=heb02b0b_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebengine=6.9.2=hebbe641_0
  - qtwebsockets=6.9.2=heb02b0b_1
  - rav1e=0.7.1=ha073cba_3
  - re2=2024.07.02=h8e466ff_4
  - requests=2.32.5=pyhcf101f3_1
  - setuptools=80.9.0=py313haa95532_0
  - shapely=2.1.2=py313h64ccc5a_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py313h5ea7bf4_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xarray=2025.12.0=pyhcf101f3_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - scipy==1.16.3
prefix: C:\Users\oliev\miniconda3\envs\olie_skew-t_demo
